<Project>
  <PropertyGroup>
    <TlVersion>1.0.0-alpha.10</TlVersion>
    <LangVersion>14</LangVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <DebugType>portable</DebugType>
    <EmbedAllSources Condition="'$(ContinuousIntegrationBuild)' == 'true'">true</EmbedAllSources>
    <PathMap Condition="'$(ContinuousIntegrationBuild)' == 'true'">$(MSBuildThisFileDirectory)=/_/</PathMap>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants Condition="('$(Configuration)' == '' or '$(Configuration)' == 'Debug') or '$(TlChecked)' == 'true'">$(DefineConstants);TL_CHECKED</DefineConstants>
  </PropertyGroup>
</Project>
