<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Play</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Tl.Core\Tl.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Tl.Gen.CSharp\Tl.Gen.CSharp.csproj" />
    <ProjectReference Include="..\..\..\tools\Tl.Gen.Tlb\Tl.Gen.Tlb.csproj" />
    <EmbeddedResource Include="..\presets\*.json" LogicalName="%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Basic.Reference.Assemblies.Net100" Version="1.8.12" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
  </ItemGroup>

</Project>
