<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WasmMainJSPath>main.mjs</WasmMainJSPath>
    <RootNamespace></RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Play.Core\Play.Core.csproj" />
  </ItemGroup>


  <Target Name="EmbedLiveReferenceAssemblies" BeforeTargets="CoreCompile">
    <ItemGroup>
      <_CoreCompileResourceInputs Include="@(ReferencePathWithRefAssemblies)" Condition="'%(Filename)' == 'Tl.Core'">
        <LogicalName>LiveRef.Tl.Core.dll</LogicalName>
      </_CoreCompileResourceInputs>
    </ItemGroup>
  </Target>

</Project>
