import json
from pathlib import Path

START = "<!-- tl-numbers: generated by eng/refresh-numbers from benchmarks/Numbers/results/numbers.json; edit the renderer, not this block -->"
END = "<!-- /tl-numbers -->"
RECEIPT_PATH = Path("benchmarks/Numbers/results/numbers.json")


def cpu_short(cpu: str) -> str:
    for marker in ("(TM) ", "(R) "):
        at = cpu.rfind(marker)
        if at >= 0:
            cpu = cpu[at + len(marker) :]
    return cpu.strip()


def load_receipt(root: Path) -> dict:
    return json.loads((root / RECEIPT_PATH).read_text(encoding="utf-8"))


def render(receipt: dict) -> str:
    scenarios = receipt["Scenarios"]
    floor = min(s["Ns"] for s in scenarios if s["Id"] != "handwritten")
    bake = receipt["Bake"]
    lines = [
        f"One million characters, one frame per call ({cpu_short(receipt['Fingerprint']['Cpu'])}, .NET 10, Release; "
        f"best of {receipt['Reps']} × {receipt['Rounds']} interleaved rounds; every shape bit-exact forward and backward, 0 B warm):",
        "",
        "| scenario | ms/frame | ns/character |",
        "| --- | ---: | ---: |",
    ]
    lines += [f"| {s['Label']} | {s['Ms']:.2f} | {s['Ns']:.2f} |" for s in scenarios]
    lines += [
        "",
        f"A single-timeline crowd floors at {floor:.2f} ns per character; grouping rows by timeline keeps every crowd on the fast rows "
        "(ECS archetypes cluster identical rows for free). "
        f"Authoring a full game's data — {bake['CorpusMb']:.1f} MB of JSON — bakes in {bake['BakeMs']:.0f} ms and loads in {bake['LoadMs']:.1f} ms. "
        "Memory: 8 B per character of host columns, `28 * (duration + 1) + 48` bytes of tables per timeline, 0 B allocated per frame at any crowd size.",
    ]
    return "\n".join(lines)


def block(readme: str) -> str:
    start = readme.index(START) + len(START)
    end = readme.index(END)
    return readme[start:end].strip("\n")


def apply(receipt: dict, readme: str) -> str:
    start = readme.index(START) + len(START)
    end = readme.index(END)
    return readme[:start] + "\n" + render(receipt) + "\n" + readme[end:]
