<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tl.CSharp" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Shared/DomainBaker.cs" Link="Shared/DomainBaker.cs" />
  </ItemGroup>
</Project>
