<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tl.Core\Tl.Core.csproj" />
    <ProjectReference Include="..\Tl.Gen.Tlb\Tl.Gen.Tlb.csproj" />
  </ItemGroup>

</Project>
