<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WaffleRoot Condition="'$(WaffleRoot)' == ''">../../../Waffle</WaffleRoot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(WaffleRoot)/src/Waffle.Core/Waffle.Core.csproj" />
    <Compile Include="../Hooks.cs" Link="Hooks.cs" />
  </ItemGroup>
</Project>
