using System.Globalization;
using Tl.Gen.Model;
using Tl.Generation;
using static Waffle.WaffleSyntax;

namespace Tl.Gen.CSharp;

public static class BakeEmitter
{
    public const int MaxBakeDuration = 1024;
    public const int MaxBakeTracks = 8;

    public static bool CanBake(TimelinePlan plan)
    {
        if (plan.Duration > MaxBakeDuration || plan.Duration == 0)
            return false;
        if (plan.MaxActiveTracks > MaxBakeTracks)
            return false;
        if (plan.Definition.Loops)
            return false;
        return true;
    }

    public static string Emit(TimelinePlan plan)
    {
        if (!CanBake(plan))
            throw new InvalidOperationException($"Plan for {plan.Definition.Name} is not eligible for specialized bake.");

        var d = plan.Definition;
        var duration = plan.Duration;
        var slotCount = plan.MaxActiveTracks;

        // Build per-tick baked data
        var wordsForward = new ulong[(int)duration + 1];
        var wordsBackward = new ulong[(int)duration + 1];

        // Format code
        return Render($$"""
            // <auto-generated />
            #nullable enable
            using System;
            using System.Runtime.CompilerServices;
            using Tl;

            namespace {{d.Namespace}};

            public static class {{d.Name}}Bake
            {
                public const uint Duration = {{duration}}u;

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static Playback Start(uint at = 0) => new(at, 0, PlaybackFlags.Started);

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                public static void RequireRunnable(in Playback playback)
                {
                    if (!playback.Has(PlaybackFlags.Started))
                        throw new InvalidOperationException("Playback was never started; mint one with Start.");
                    if (playback.Has(PlaybackFlags.Stopped))
                        throw new InvalidOperationException("Playback is stopped.");
                }
            }
            """);
    }
}
