using System.Globalization;
using Tl.Gen.Model;
using static Waffle.WaffleSyntax;

namespace Tl.Gen.CSharp;

public static class TableEmitter
{
    public static string Emit(TimelinePlan plan)
    {
        var d = plan.Definition;

        var regionStartsStr = string.Join(", ", plan.RegionStarts.Select(s => s.ToString(CultureInfo.InvariantCulture) + "u"));
        var regionRowsStr = string.Join(", ", plan.RegionRows.Select(r => $"new({r.TrackStart}, {r.TrackCount})"));
        var trackRowsStr = string.Join(", ", plan.TrackRows.Select(t => $"new({t.TrackIndex}, {t.ClipStart}, {t.ClipCount})"));
        var clipRowsStr = string.Join(", ", plan.ClipRows.Select(c => $"new({c.ClipIndex}, {c.FactorStart}u, {c.FactorLength}u)"));
        var clipEdgesStr = string.Join(", ", plan.ClipEdges.Select(e => $"new({e.Start}u, {e.End}u)"));

        var trackDataStr = string.Join(", ", d.Tracks.Select(t => $"new {d.Name}()"));
        var clipDataStr = string.Join(", ", d.Clips.Select(c => c.PayloadExpression));

        var blendBody = d.BlendMethodBody ?? "result = first;";

        return Render($$"""
            // <auto-generated />
            #nullable enable
            using System;
            using Tl;
            using Tl.Generation;

            namespace {{d.Namespace}};

            public readonly struct {{d.Name}} : ITrackTables<{{d.Name}}, {{d.ClipTypeName}}>, IBlend<{{d.ClipTypeName}}>
            {
                private static readonly uint[] s_regionStarts = [{{regionStartsStr}}];
                private static readonly RegionRow[] s_regionRows = [{{regionRowsStr}}];
                private static readonly TrackRow[] s_trackRows = [{{trackRowsStr}}];
                private static readonly ClipRow[] s_clipRows = [{{clipRowsStr}}];
                private static readonly ClipEdge[] s_clipEdges = [{{clipEdgesStr}}];
                private static readonly {{d.Name}}[] s_trackData = [{{trackDataStr}}];
                private static readonly {{d.ClipTypeName}}[] s_clipData = [{{clipDataStr}}];

                public static ReadOnlySpan<uint> RegionStarts => s_regionStarts;
                public static ReadOnlySpan<RegionRow> RegionRows => s_regionRows;
                public static ReadOnlySpan<TrackRow> TrackRows => s_trackRows;
                public static ReadOnlySpan<ClipRow> ClipRows => s_clipRows;
                public static ReadOnlySpan<ClipEdge> ClipEdges => s_clipEdges;
                public static ReadOnlySpan<{{d.Name}}> TrackData => s_trackData;
                public static ReadOnlySpan<{{d.ClipTypeName}}> ClipData => s_clipData;
                public static bool Loops => {{d.Loops.ToString().ToLowerInvariant()}};

                public void Blend(in {{d.ClipTypeName}} first, in {{d.ClipTypeName}} second, float t, out {{d.ClipTypeName}} result)
                {
                    {{blendBody}}
                }
            }
            """);
    }
}
